### ISSUE TITLE
***Checksum***

### ISSUE THREAD

**Issue by xuryann** [Yonder-Deep/Nautilus#1]
Used for error detection when communicating via radio

**Comment by stephenbusi** [comment]
CRC 16 or 32

**Comment by stephenbusi** [comment]
**Corrupted Messages**
BS -> AUV
Navigation Command:
- ignore the message
Mission Command:
- BS waits for response
- Send mission command again if Mission Status Data not in-progress

AUV -> BS:
- ignore
- Leave in format of    Position: X (Last received 85)

**Comment by ServiceDog** [comment]
On closure, please reference the pull request number or commit hash which implements this feature request. Otherwise there's no indication that this feature was pushed to Main without investigating the code base

**Comment by stephenbusi** [comment]
Continued in different issue ticket [here](https://github.com/Yonder-Deep/Nautilus/issues/4)
