### ISSUE TITLE
requirements.txt needs cleaning up for base_station

### ISSUE THREAD

**Issue by DaPhysikist** [Yonder-Deep/Nautilus#102]
Please clean up this text file to only use pip imports that we need. Will make it much easier for new recruits doing a fresh install of all library dependencies for the project. I added ones that we began using recently, such as adafruit-circuitpython-gps and serial, but there are many here that are most likely not needed and cause issues when ./install.cmd is called.

**Comment by Girish-Krishnan** [comment]
Working on it - there's a library called pipreqs which makes this easy.
