### ISSUE TITLE
GPS implementation on AUV and BS

### ISSUE THREAD

**Issue by stephenbusi** [Yonder-Deep/Nautilus#35]
need to figure out how to read in GPS data and send it over radio

**Comment by asabbani** [comment]
New members can start by looking at this issue.

**Comment by abiramisabbani** [comment]
Update positioning on map from gps
Have relative positioning sent back to base station
Maybe give Base Station gps to better allow for relative positioning
Have coordinates work on the map for autonomous, horizontal movement
Allow user to type in a coordinate
Allow user to click on map
