### ISSUE TITLE
Implement motor test commands

### ISSUE THREAD

**Issue by stephenbusi** [Yonder-Deep/Nautilus#37]
- [x] GUI button triggers function call
- [x] send command over BS radio
- [x] implement receive ifelse in AUV.py
- [x] add to motor queue
- [ ] implement test function
  - Left and Right - 90 degree turn
  - Forward - 5m forward
  - Backward - 5m backward
  - Down - 5m down

**Comment by xuryann** [comment]
- GPIO and PI pins for each motor are not correct and need to be updated with the correct ones
- waiting for GPS functionality to finish with the motor tests

**Comment by DaPhysikist** [comment]
yeah this was done lol
