### ISSUE TITLE
***Add Checksum (CRC 16 or 32)***

### ISSUE THREAD

**Issue by stephenbusi** [Yonder-Deep/Nautilus#4]
Need to add checksum for all encoded commands/messages

**Comment by ServiceDog** [comment]
In future issues always provide rationale on closure, such as "duplicate issue, see #1"

**Comment by stephenbusi** [comment]
### Checksum
commit: [464ad9964a87e6e77f3ea64a1e0f62159f838125](https://github.com/Yonder-Deep/Nautilus/commit/464ad9964a87e6e77f3ea64a1e0f62159f838125)
- implemented through a new Crc32 class in both AUV and Basestation API
- Checksum automatically attached on radio write calls
