### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by stephenbusi** [Yonder-Deep/Nautilus#64]
1. Separate Receive and Send thread classes into new files 
2. Create new Constants files
3. Remove unused functions, classes, and variables
4. split run() method in each class into smaller functions 
5. Update code comments

**Comment by stephenbusi** [comment]
Basestation Refactoring: https://docs.google.com/document/d/1O70Ru1EJTspxtO3G0YvSOusL-K6dkPmfdE5f6VheGdY/edit?usp=sharing
AUV Refactoring: https://docs.google.com/document/d/18gTte-em_Ju0GLhEE36lH2hEC6RCJPoBbuAqY3sYCA8/edit?usp=sharing

**Comment by ServiceDog** [comment]
If multiple files declare gpio pin assignments, might want to split off a gpio config file so they're on the same page, easier to move pins around if needed

**Comment by stephenbusi** [comment]
Looks like right now, we only reference gpio pins in the motor_controller file. If we add more references in other files later on, we'll make a gpio file then.
